export const CHANGE_POSITION = "CHANGE_POSITION";

export const UPDATE_APPLICANTS_LIST = {
  REQUEST: "UPDATE_APPLICANTS_LIST_REQUEST",
  SUCCESS: "UPDATE_APPLICANTS_LIST_SUCCESS",
  FAILURE: "UPDATE_APPLICANTS_LIST_FAILURE",
};
