export const CREATE_FORM_ITEM = {
  REQUEST: "CREATE_FORM_ITEM_REQUEST",
  SUCCESS: "CREATE_FORM_ITEM_SUCCESS",
  FAILURE: "CREATE_FORM_ITEM_FAILURE"
};

export const UPDATE_FORM_ITEM = {
  REQUEST: "UPDATE_FORM_ITEM_REQUEST",
  SUCCESS: "UPDATE_FORM_ITEM_SUCCESS",
  FAILURE: "UPDATE_FORM_ITEM_FAILURE"
};

export const REMOVE_FORM_ITEM = {
  REQUEST: "REMOVE_FORM_ITEM_REQUEST",
  SUCCESS: "REMOVE_FORM_ITEM_SUCCESS",
  FAILURE: "REMOVE_FORM_ITEM_FAILURE"
};
